fixed some mistakes
Sofasmile/MA_HomeWork pull request #2
Opened 2019-03-09 14:31 UTC by Sofasmile

https://github.com/Sofasmile/MA_HomeWork/pull/1 - посилання на старий ПР, не змогла його виправити, так щоб не було файлу .gitignore

2019-03-09 18:43 UTC, Taniann requested changes
please make a little fixing

2019-03-09 18:43 UTC, Taniann commented on src/java.com/homework5/Calculator.java
> +    public void calculate(double a, double b, char c) {
better make it static
and return double instead of printing result in method

2019-03-09 19:00 UTC, Sofasmile commented
Виправила зауваження) Потрібно знову призначати в таблиці?

9 березня 2019, 20:44:00, від "Tania Nebesna" <notifications@github.com>:

@Taniann requested changes on this pull request.
please make a little fixing
In src/java.com/homework5/Calculator.java:
>  
+public class Calculator {
+    public void calculate(double a, double b, char c) {
better make it static
and return double instead of printing result in method
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-03-10 14:26 UTC, Taniann approved these changes
good

2019-03-10 15:45 UTC, merged